version: "3.8"

services:
  proxy:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host"

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

